package trabalho1;

import java.util.ArrayList;
import java.util.List;

public class TabelaDeTipos {

  private ArrayList<Tipo> tipos;

  public TabelaDeTipos() {
    tipos = new ArrayList<Tipo>();
  }

  public void adicionarTipo(String nome, Boolean basic, Boolean autoGenerated) {
    tipos.add(new Tipo(nome, basic, autoGenerated));
  }
  public void adicionarTipo(Tipo novoTipo) {
    tipos.add( novoTipo );
  }

  public void adicionarTipos(List<String> nomes, Boolean basic, Boolean autoGenerated) {
    for(String nome : nomes) {
      tipos.add(new Tipo(nome, basic, autoGenerated));
    }
  }

  public boolean existeTipo(String nome) {
    nome = nome.replace("^", "");
    for(Tipo tipo : tipos) {
      if(tipo.getNome().equals(nome)) {
        return true;
      }
    }
    return false;
  }
}
