package trabalho1;

public class Tipo {
  private String nome;
  private Boolean basic;
  private Boolean autoGenerated;
  private List<Simbolo> dados;

  public void Tipo( String nome, Boolean basic, Boolean autoGenerated ) {
    this.nome = nome;
    this.basic = basic;
    this.autoGenerated = autoGenerated;
    dados = new ArrayList<Simbolo>();
  }

  public void addSimbolo( String nome, String tipo ) {
    Simbolo simbolo = new Simbolo( nome, tipo );
    addSimbolo( simbolo );
  }

  public void addSimbolo( Simbolo simbolo ) {
    dados.add( simbolo );
  }

  public Boolean hasSimbolo ( String nome ) {
    if ( !basic ) {
      for( Simbolo s: dados ) {
        if (s.getNome() == nome ) {
          return true;
        }
      }
    }
    return false;
  }

  public Simbolo getSimbolo ( String nome ) {
    if ( !basic ) {
      for( Simbolo s: dados ) {
        if (s.getNome() == nome ) {
          return s;
        }
      }
    }
    return null;
  }

  public String getNome() {
    return nome;
  }

  public Boolean isBasic() {
    return basic;
  }
  
  public Boolean isAutoGenerated() {
    return autoGenerated;
  }
}
